### ISSUE TITLE
Separar o código e usar make para compilar

### ISSUE THREAD

**Issue by romcenci** [romcenci/DynamicSimulator#14]
Acho que o código ta ficando muito grande, deveríamos separar ele em alguns pedaços e começar a compilar com um Makefile.
Até porque ele pode começar a demorar pra compilar depois que adicionarmos o GTK.
E vamos combinar que tá uma gambiarra dentro do DynSim.sh.
Você pode nos ajudar nessa empreitada, @francosauvisky?
A maior dificultade que vejo em fazer isso é que vamos precisar mudar o jeito de passar os argumentos pro C, talvez jogar fora o DynSim.sh e voltar a interpretar as flags de dentro do C.

**Comment by francosauvisky** [comment]
Abri uma issue pro getopt e criei o Makefile
