### ISSUE TITLE
Zoom estranho no modo 1

### ISSUE THREAD

**Issue by romcenci** [romcenci/DynamicSimulator#16]
Dar zoom no modo 1d deveria transformar toda a cena, e não só o atual.
Mas como não guardamos a posição de tudo, fica difícil.

**Comment by Leo-Souto** [comment]
Acho que o ideal do modo 1 seria printar 0 ou 1 com ter ou não ter pontos dentro do pixel. aí daria pra guardar tudo em matriz e plotar.

**Comment by romcenci** [comment]
Isso ai, guardei a posição de cada partícula, mais ou menos como no modo 0, dai ficou muito bom, acabou resolvendo o bug de ficar piscando também.

**Comment by Leo-Souto** [comment]
A ideia de não limpar os pixels é uma gambiarra grande demais pra funcionar direito kkk.
