### ISSUE TITLE
Escala de cores

### ISSUE THREAD

**Issue by romcenci** [romcenci/DynamicSimulator#17]
Acho que já podemos começar a pensar numa forma de escolher a escala de cores do modo 0 e 2 e como passar isso pro shell script.

**Comment by Leo-Souto** [comment]
Pensei em algo do tipo:

Uma matriz
r1 g1 b1
r2 g2 b2
.
.
.
rn gn bn

Aí a linha seria acessada fazendo:
Floor(valor*número de linhas);
Valor = [0:1]
A parte mais problemática seria carregar essa matriz na interface.

**Comment by Leo-Souto** [comment]
O DynamicLattice não era diferente, tinha que criar um doc com linhas.

**Comment by Leo-Souto** [comment]
Pra parte do shellscript acho que teria que aceitar uma string com o nome do arquivo. Aí transforma numa matriz usando fscanf.

**Comment by romcenci** [comment]
Ok, fiz uma tentativa aqui: https://github.com/romcenci/DynamicSimulator/commit/f601f1004f40be33cb768a2581e2856d4c1a5d17.
Já parece estar funcionando bacana, sem precisar de muito, a não ser uma função pra ler do arquivo.
Coisas que tem que fazer pra fechar o commit:
- [ ] Background ta pintando no modo 0, tem que resolver.
- [ ] Ta tudo jogado *R *G e *B, talvez colocar esses três em uma struct, deixaria mais bonito.
- [ ] Colocar no README como escolher as cores.
- [ ] Talvez usar um spline cubico ao invés da interpolação linear, pq as cores intermediárias não aparecem muito.

**Comment by romcenci** [comment]
Três cores fica estranho, pq tem uma mudança brusca no ponto do meio, o spline cubico provavelmente vai resolver e dai fica bonito.
![screenshot](https://user-images.githubusercontent.com/28690931/44629580-e1af9780-a927-11e8-9ae3-1b1da790e9fd.png)

**Comment by Leo-Souto** [comment]
com color.txt tá rodando bem, acho que as cores estão esquisitas pq a interpolação é no RGB, vou trabalhar numa conversão para HSL.

**Comment by Leo-Souto** [comment]
Vou me basear no algoritmo desse link, p. 303;

https://link.springer.com/book/10.1007/b138805

**Comment by Leo-Souto** [comment]
RGB2HSV e HSV2RGB implementadas, falta integrar ao resto do algoritmo.

**Comment by romcenci** [comment]
@Leo-Souto, eu dei push na interpol no HSV, ve ai como ficou.

**Comment by Leo-Souto** [comment]
Tá dando um bocado de erros de declaração, vou tentar resolver

**Comment by romcenci** [comment]
Que vamos fazer nesse daqui, @Leo-Souto?
Acho que podemos deixar como está, a paleta ta implementada, único problema é quando quer que apareça mais de 2 cores, é um pouco frescura tbm.
Acho que ninguém quer ficar com 3 cores no plot de qquer jeito kkk, se tiver precisando dai vai abrir um issue específico.

**Comment by romcenci** [comment]
@Leo-Souto, vê como está agora.
Consegui fazer funcionar com interpol linear, era só fazer a transformação da interpolação do jeito certo, :unamused:.
Mas agora acho que ta top, vê ai, se tiver de acordo podemos fechar aqui.

**Comment by Leo-Souto** [comment]
Como que tá sendo rodado agora?

**Comment by romcenci** [comment]
Mesmo jeito, a principio.

**Comment by Leo-Souto** [comment]
Parece bom para mim, só tem que incluir a instalação do yad no readme.
