### ISSUE TITLE
Pause criando linhas brancas

### ISSUE THREAD

**Issue by Leo-Souto** [romcenci/DynamicSimulator#26]
Não olhei no código, mas acho que tem que subtrair 1 do tempo, ele deve estar pulando o índice no loop quando reinicia.
![captura de tela de 2018-08-24 17-50-54](https://user-images.githubusercontent.com/16999127/44607386-ab0e3b80-a7c6-11e8-8df8-abb71067f698.png)

**Comment by Leo-Souto** [comment]
Verifiquei o código aqui, não é isso, alguma ideia?

**Comment by romcenci** [comment]
Acho que https://github.com/romcenci/DynamicSimulator/commit/f601f1004f40be33cb768a2581e2856d4c1a5d17 resolveu isso, @Leo-Souto .
Testa ai, se funcionou já pode fechar, daí.

**Comment by Leo-Souto** [comment]
Corrigido
