### ISSUE TITLE
Coisas para arrumar no modo 5

### ISSUE THREAD

**Issue by romcenci** [romcenci/DynamicSimulator#28]
Algumas coisas pra fazer no modo 5:
- [x] Zoom
- [x] Pause
- [x] Começo fora do centro
- [x] Colocar no readme
 
- [ ] Opções para 1D, 2D e 3D no getopts()
- [ ] Paleta de cores

**Comment by Leo-Souto** [comment]
#28 Corrigido cores diferentes nas flechas, para cada glvertex é necessário um glcolor. Also, limpei o draw de funções superfluas.

**Comment by romcenci** [comment]
Deu ruim aqui, Léo.
```
/tmp/ccE19r88.o: In function `main':
main.c:(.text+0x83a): undefined reference to `DrawFrame'
collect2: error: ld returned 1 exit status
Makefile:25: recipe for target 'src/main' failed
make: *** [src/main] Error 1
```
