### ISSUE TITLE
referência indefinida a símbolo "pow@@GLIBC_2.2.5"

### ISSUE THREAD

**Issue by celofsco** [romcenci/DynamicSimulator#29]
Quando faço o make retorna esse erro
$ make
gcc src/main.c -lm -lGL -lglfw -o DynSim src/libbmp/libbmp.o src/colors.o src/draws.o src/modes.o src/other.o
/usr/bin/x86_64-linux-gnu-ld: src/draws.o: referência indefinida a símbolo "pow@@GLIBC_2.2.5"
/lib/x86_64-linux-gnu/libm.so.6: erro ao adicionar símbolos: DSO em falta da linha de comandos
collect2: error: ld returned 1 exit status
Makefile:26: recipe for target 'src/main' failed
make: *** [src/main] Error 1

**Comment by romcenci** [comment]
Cara, tenta instalar a libc6:
`sudo apt-get install libc6`
Acho estranho pq isso já deveria estar no debian.
