### ISSUE TITLE
Pensar sobre arquivo de config

### ISSUE THREAD

**Issue by romcenci** [romcenci/DynamicSimulator#35]
@Leo-Souto, tava pensando numa ideia aqui de ao invés de ficar passando tantas coisas pro ./DynSim por getopt, podiamos colocar as opções numa especie de arquivo de configuração, e toda vez que roda-se o simulador ele leria as opções no arquivo. 

Pq não faz sentido tipo, se eu uso o modo 3, eu preciso toda vez colocar "-m 3" sendo que isso já poderia estar fixo. Só vou usar outra opção em outros projetos, mas ai da pra mudar o arquivo de configuração, ou manter o getopts junto com esse arquivo.

**Comment by Leo-Souto** [comment]
Poisé, eu tava pensando nisso esses dias, seria meio chato ter que ficar se preocupando com isso quando tiver uma interface gráfica. acho que poderia ter as duas opções, tipo, se # argv == 0, procurar tal arquivo com as configurações. caso contrário, coletar os parâmetros da linha de comando. Na interface gráfica poderia ter um "Settings", que a pessoa modificaria os parâmetros. Mas aí faria alguns error handlers pra cuidar disso. O problema é que o curso de Qt não explica integração com OpenGL, e os que eu achei no youtube são todos de versões mais antigas.

**Comment by romcenci** [comment]
Legal, vou tentar fazer esse arquivo de config agora, vamo ver como fica.

**Comment by romcenci** [comment]
Ta, @Leo-Souto e se ao invés de usar o dsconfig como tá agora tivesse um cabeçalho nos próprios dados com # que dizem o modo e tal, como o dsconfig, mas sem precisar de um arquivo separado para tal, podendo o próprio código já passar as opções.

**Comment by Leo-Souto** [comment]
Vai ser por dsconfig, se o usuário quiser, ele pode gerar o arquivo config direto no código dele.
