### ISSUE TITLE
Tentar otimizar usando própria máquina de estado

### ISSUE THREAD

**Issue by romcenci** [romcenci/DynamicSimulator#39]
Não precisa atualizar todo o grid, apenas não limpa a tela e usa a máquina de estado para o desenho ficar salvo.

Tem que cuidar pra ver como fazemos o zoom e se isso não afeta.

**Comment by romcenci** [comment]
No meu computador fazer isso não deu certo, fica dando flickering.

**Comment by Leo-Souto** [comment]
Não funciona.
