### ISSUE TITLE
Opts para escala do plot

### ISSUE THREAD

**Issue by romcenci** [romcenci/DynamicSimulator#7]
Colocar algumas opções no ./DynSim.sh para arrumar o plot: -xrange -yrange

**Comment by romcenci** [comment]
Estavámos fazendo isso, @Leo-Souto? Não lembro qual era o arquivo que estavámos mexendo.

**Comment by Leo-Souto** [comment]
Pois então, o algoritmo que tá aqui não tá totalmente atualizado, o que tá no labstat tá mais novo, mas também não é o que a gente estava mexendo, não consegui encontrar o verdadeiro. Passa no lab amanhã pra gente ver isso.

**Comment by romcenci** [comment]
Ok, vamos começar de novo então, se tiver alguma coisa manda pra gente tomar como base.
Resumindo, o que precisamos fazer é colocar nisso https://github.com/romcenci/DynamicSimulator/blob/81687094f6b9f75a02a34775f129cc03249d3b7c/DynSim.sh#L1-L29 umas opções como --xSize --ySize.
E a ideia também era conseguir dar zoom por meio de uma opção, tipo --xRange --yRange, lembra?
Então, futuramente, podíamos colocar opção pra fazer isso interativamente, pelo mouse. 
Ficaria muito legal.

**Comment by romcenci** [comment]
Olha só, consegui fazer alguma coisa aqui:
https://github.com/romcenci/DynamicSimulator/blob/7b80c1041c4fb302e845391f79e88bad59e34fa2/DynSim_LongOpts.sh#L1-L30
Não sei se ficou muito intuitivo, é uma coisa tipo:
`./a.out | ./DynSim -m 2 -l 300 --height=100 --width=100`
E dai ficou a tela bem pequena, do tamanho que eu escolhi.
Só não sei mesmo se esse jeito de colocar as opções longas é o melhor, com o = e tal, meio estranho.
O que você acha?

**Comment by romcenci** [comment]
Temos que fazer longopts da mesma forma que opts, sem o sinal de igual, uma das opções é usar algo assim:

```# Transform long options to short ones
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--rest") set -- "$@" "-r" ;;
    "--ws")   set -- "$@" "-w" ;;
    *)        set -- "$@" "$arg"
  esac
done

# Default behavior
rest=false; ws=false

# Parse short options
OPTIND=1
while getopts "hrw" opt
do
  case "$opt" in
    "h") print_usage; exit 0 ;;
    "r") rest=true ;;
    "w") ws=true ;;
    "?") print_usage >&2; exit 1 ;;
  esac
done
shift $(expr $OPTIND - 1) # remove options from positional parameters```

Pra converter as opções longas para curtas.
